{
	"version": 1675613273,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/background-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/off2-sheet0.png",
		"images/on2popup-sheet0.png",
		"images/bgsettingpopup-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/on3popup-sheet0.png",
		"images/close-sheet0.png",
		"images/offmusik-sheet0.png",
		"images/backgroundselectlevel-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite3-sheet2.png",
		"images/sprite3-sheet3.png",
		"images/sprite3-sheet4.png",
		"images/sprite3-sheet5.png",
		"images/sprite3-sheet6.png",
		"images/sprite3-sheet7.png",
		"images/sprite3-sheet8.png",
		"images/sprite3-sheet9.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/sprite16-sheet0.png",
		"images/sayur-sheet0.png",
		"images/win1-sheet0.png",
		"images/next1-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/box1-sheet0.png",
		"images/box1-sheet1.png",
		"images/box1-sheet2.png",
		"images/siluet-sheet0.png",
		"images/siluet-sheet1.png",
		"images/siluet-sheet2.png",
		"images/particles.png",
		"images/particles2.png",
		"images/tryagain1-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite21-sheet1.png",
		"images/sprite22-sheet0.png",
		"images/siluetbox2d-sheet0.png",
		"images/box2d-sheet0.png",
		"images/box2d-sheet1.png",
		"images/box2d-sheet2.png",
		"images/keretalvl2-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/boxlvl2-sheet0.png",
		"images/siluetboxlvl2-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/sprite30-sheet0.png",
		"images/wadah-sheet0.png",
		"images/wadah-sheet1.png",
		"images/objeklvl8-sheet0.png",
		"images/objeklvl8-sheet1.png",
		"images/objeklvl8-sheet2.png",
		"images/objeklvl8-sheet3.png",
		"images/kardusatas-sheet0.png",
		"images/back-sheet0.png",
		"images/sprite32-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/loadinginti-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/tempat6-sheet0.png",
		"images/tempat6-sheet1.png",
		"images/tempat6-sheet2.png",
		"images/balok6-sheet0.png",
		"images/balok6-sheet1.png",
		"images/balok6-sheet2.png",
		"images/sprite37-sheet0.png",
		"images/siluetbaloktutup-sheet0.png",
		"images/siluetbaloktutup-sheet1.png",
		"images/siluetbaloktutup-sheet2.png",
		"images/objek4-sheet0.png",
		"images/siluetpuzzle-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/siluetpuzzlejadi-sheet0.png",
		"images/siluetpuzzlejadi-sheet1.png",
		"images/siluetpuzzlejadi-sheet2.png",
		"images/siluetpuzzlejadi-sheet3.png",
		"images/pilihlevel-sheet0.png",
		"images/cluepuzzle-sheet0.png",
		"images/kertaspapan-sheet0.png",
		"images/titik5-sheet0.png",
		"images/garis-sheet0.png",
		"images/sprite38-sheet0.png",
		"images/papankayugambar-sheet0.png",
		"images/kertasputih-sheet0.png",
		"images/warna-sheet0.png",
		"images/canvas2.png",
		"images/kertaswarna.png",
		"images/kursor-sheet0.png",
		"images/color.png",
		"images/line.png",
		"images/pipe.png",
		"images/selesai-sheet0.png",
		"images/buahkiri-sheet0.png",
		"images/garis3-sheet0.png",
		"images/buahkanan-sheet0.png",
		"images/buahkanan-sheet1.png",
		"images/clue-sheet0.png",
		"media/inspiring cinematic background music by infraction [no copyright music] _ fantasia.ogg",
		"media/musik-como.ogg",
		"media/click-button.ogg",
		"media/click-start-button.ogg",
		"media/kamu luar biasa.ogg",
		"media/kamu pasti bisa.ogg",
		"media/clue level 1.ogg",
		"media/clue level 10.ogg",
		"media/clue level 2.ogg",
		"media/clue level 3.ogg",
		"media/clue level 4.ogg",
		"media/clue level 5.ogg",
		"media/clue level 6.ogg",
		"media/clue level 8.ogg",
		"media/clue level 9.ogg",
		"media/clue level 7.ogg",
		"media/clue level 7-[audiotrimmer.com].ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}